name: workflow_02
on: [repository_dispatch]
#on:
#  push:
#    branches: [ master ]
jobs:
  run_program:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with: 
          repository: MrSmid/ci_proj
          ref: master
          
      - name: Run
        run: java Main.java
